---
title: "Tidy Data"
author: "Anna Ma"
date: "10/3/2021"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
#we don't see anything here in the output, just things that we do ourselves in the background
library(tidyverse)
library(readxl)
library(haven)
```

## Piviot longer

Load the PULSE data

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

Let's try to pivot

```{r}
# if your variable share the same prefix and you don't need that prefix in everything, use names_prefix ="the part u don't want"
#
pulse_tidy = 
  pulse_df %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, #taking the columns from bl to 12m
    names_to = "visit",         #pivot the column to a variable names visit
    names_prefix = "bdi_score_", # getting rid of the prefix bdi_score_
    values_to = "bdi"   
    #pivot all the value from original column bl-12m to a variable names bdi
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m"), 
    #replacing bl with 00m to have consistent naming
    visit = factor(visit) # converting visit to a factor variable 
  )
```

## Pivot_wider example

make up a results data table

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control","control"),
    time = c("a","b","a","b"),
    group_mean = c(4,8,3,6)
  )

analysis_df %>%
  pivot_wider(
    names_from = "time",
    values_from = "group_mean"
  ) %>% 
  knitr::kable() #formatting the table so it's easier read 
```


