---
title: "Data Manipulation"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
#we don't see anything here in the output, just things that we do ourselves in the background
library(tidyverse)
```

## Import some data

I want to import `FAS_litters.csv`;

```{r}
# taken directly from the data folder in our current directory
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```

## `Select`

Let's select some columns.

```{r， eval=FALSE}
#select cols that I'm interested about
select(litters_df, group, litter_number)
select(litters_df, group, gd0_weight, gd18_weight)

#taking everything from gd0_weight to gd_of_birth
select(litters_df, group, gd0_weight:gd_of_birth)

#everything except litter number 
select(litters_df, -litter_number)

#start with or end with 
select(litters_df, grouos, starts_with("pups"))

#rename a col
select(litters_df, GROUP = group, litter_number)

#not selecting anything, but renaming 
rename(litters_df, GROUP = group)

# select in the order that i want/ relocate litter number to the first col
select(litters_df, litter_number, everything())

#similarly, we can do 
relocate(litters_df,litter_number)

select(litters_df,group) #gives a data frame with just one col

#pull(litters_df, group) #extract out the col
```

```{r, eval=FALSE}
#exercise: select the columns containing litter number, sex, and pd ears from pups data
select(pups_df, litter_number, sex, pd_ears)
```

## `filter`

```{r}
#if true, keep, if not, omit
# single equal sign put a thing to a variable, double equal sign "==" actually compares whether two things are equal 

filter(litters_df, gd_of_birth == 20)
filter(litters_df, group == "Con7")

filter(litters_df, gd0_weight < 23)

filter(litters_df, pups_survive != 4)

filter(litters_df, !(group == "Con7"))

filter(litters_df, group %in% c("Con7", "Con8"))

filter(litters_df, group == "Con7", gd_of_birth == 20)

# filter(litters_df, group == "Con7" | gd_of_birth == 20) or 
# filter(litters_df, group == "Con7" & gd_of_birth == 20) same with using a comma 

#get rid of all missing value
drop_na(litters_df)

#get rid of the missing value in this variable
drop_na(litters_df, gd0_weight)
```

```{r}
#exercise 
filter(pups_df, sex == 1)
```


## `Mutate`

Let's add or change columns!

```{r}
mutate(
  litters_df, 
  weight_change = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```

## `arrange`

Let's rearrange the data

```{r}
# default is ascending
arrange(litters_df, gd_of_birth, gd0_weight)
#arrange(litters_df, desc(gd0_weight))
```

## Pipes

```{r}
#Without pipe
litters_data_raw = read_csv("data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_select = select(litters_clean_name, group, pups_survive)
litters_filtered = filter(litters_select, group == "Con7")

# short cut for pipe is shift+command+m
litters_df = 
  read_csv("data/FAS_litters.csv") %>%
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    weight_change = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  ) %>% 
  drop_na(weight_change) %>% 
  filter(group %in% c("con7","con8")) %>% 
  select(litter_number,group,weight_change,everything())

```

